# Generated by Django 5.2.6 on 2025-10-21 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0002_alter_diagnostico_tipo_solucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('notas_entrega', models.TextField(blank=True)),
                ('diagnostico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.diagnostico')),
                ('entregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
