# Generated by Django 5.2.6 on 2025-10-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('tecnico', 'Técnico'), ('admin', 'Administrador')], default='admin', max_length=10),
        ),
    ]
