# Generated by Django 5.2.6 on 2025-10-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='tipo_solucion',
            field=models.CharField(choices=[('correctiva', 'Correctiva'), ('preventiva', 'Preventiva'), ('predictiva', 'Predictiva')], max_length=50),
        ),
    ]
